// src/pipeline/ticketer.ts
import crypto from "node:crypto";
import type { AnalysisResult } from "../types.js";
import type { JiraClient } from "../integrations/jira.js";
import { sanitizeLogSamples } from "../utils/sanitizer.js";
import { logger } from "../utils/logger.js";

function shortHash(input: string): string {
  return crypto.createHash("sha256").update(input).digest("hex").substring(0, 12);
}

export interface TicketResult {
  key: string;
  url: string;
  created: boolean;  // false if found via idempotency check
}

export async function createTicket(
  analysis: AnalysisResult,
  priority: string,
  projectKey: string,
  jiraClient: JiraClient,
  sourceId?: number,
  exampleMessage?: string
): Promise<TicketResult> {
  // Idempotency: use a stable short hash of the pattern as a label for reliable lookup
  const patternTag = `pattern-${shortHash(analysis.errorPattern)}`;
  const jql = `labels = "${patternTag}" AND project = "${projectKey}" AND status != Done`;

  try {
    const existing = await jiraClient.searchIssues(jql);
    if (existing.length > 0) {
      logger.info("Found existing Jira ticket", { key: existing[0].key, pattern: analysis.errorPattern });
      return {
        key: existing[0].key,
        url: jiraClient.getIssueUrl(existing[0].key),
        created: false,
      };
    }
  } catch (err) {
    logger.warn("Jira search failed, proceeding with creation", { error: String(err) });
  }

  // Build a human-readable summary — prefer actual error text over pattern hash
  const readable = exampleMessage || analysis.rawLogSamples[0] || analysis.rootCauseHypothesis || analysis.errorPattern;
  const shortDesc = readable.substring(0, 150).replace(/\n/g, " ");
  const summary = `[Auto] ${analysis.service} (${analysis.environment}): ${shortDesc}`.substring(0, 250);

  // Sanitize log samples
  const sanitizedSamples = sanitizeLogSamples(analysis.rawLogSamples);

  // Build BetterStack logs URL if we have a source ID (use sanitized sample to avoid leaking secrets)
  const logsUrl = sourceId
    ? `https://logs.betterstack.com/source/${sourceId}/tail?query=${encodeURIComponent(sanitizedSamples[0]?.substring(0, 100) || analysis.errorPattern)}`
    : undefined;

  // Build description
  const description = buildDescription(analysis, sanitizedSamples, logsUrl);

  // Labels — include patternTag for idempotent lookup
  const labels = ["auto-detected", "log-monitor", analysis.service, analysis.environment, patternTag];

  // Create ticket
  const result = await jiraClient.createIssue(projectKey, summary, description, priority, labels);
  logger.info("Created Jira ticket", { key: result.key, pattern: analysis.errorPattern });

  return {
    key: result.key,
    url: result.url,
    created: true,
  };
}

function buildDescription(analysis: AnalysisResult, sanitizedSamples: string[], logsUrl?: string): string {
  const sections = [
    `Error Pattern: ${analysis.errorPattern}`,
    `Component: ${analysis.component}`,
    `Category: ${analysis.category}`,
  ];

  if (logsUrl) {
    sections.push("", `BetterStack Logs: ${logsUrl}`);
  }

  sections.push(
    "",
    `Root Cause Hypothesis:`,
    analysis.rootCauseHypothesis,
    "",
    `Suggested Approach:`,
    analysis.suggestedApproach,
    "",
    `Affected Files:`,
    ...analysis.affectedFiles.map((f) => `- ${f} ${analysis.relevantLines ? `(${analysis.relevantLines})` : ""}`),
    "",
    `Raw Log Samples (sanitized):`,
    ...sanitizedSamples.map((s, i) => `${i + 1}. ${s}`),
    "",
    "---",
    "This ticket was auto-generated by the Log Monitor pipeline.",
  );

  return sections.join("\n");
}
